In [1]:
import pandas as pd
import streamlit as st
import altair as alt
from geopy.geocoders import GoogleV3
import folium
import numpy as np
from utils import get_filtered_counts, mapped_colors, races
import geopandas as gpd

In [2]:
gdf = gpd.read_file('TOWNSSURVEY_POLY.shp')
gdf

,TOWN,TOWN_ID,POP1980,POP1990,POP2000,POPCH90_00,TYPE,ISLAND,COASTAL_PO,FOURCOLOR,...,FIPS_MCD,FIPS_COUNT,ACRES,SQUARE_MIL,POP2010,POPCH00_10,POPCH80_90,SHAPE_AREA,SHAPE_LEN,geometry
0,WESTPORT,334,13861,13852,14183,331,T,1,NO,1,...,25005100,5,0.942,0.002,15532,1349,-9,3.810934e+03,310.959400,"POLYGON ((236386.252 808384.495, 236380.123 80..."
1,FALMOUTH,96,25007,27960,32660,4700,T,1,NO,2,...,25001035,1,3.695,0.006,31531,-1129,2953,1.495345e+04,498.058255,"POLYGON ((268360.782 808386.365, 268347.943 80..."
2,WESTPORT,334,13861,13852,14183,331,T,1,NO,1,...,25005100,5,0.433,0.001,15532,1349,-9,1.753456e+03,278.276059,"POLYGON ((233335.013 809394.755, 233340.333 80..."
3,FALMOUTH,96,25007,27960,32660,4700,T,1,NO,2,...,25001035,1,0.157,0.000,31531,-1129,2953,6.358812e+02,109.461733,"POLYGON ((277887.593 814023.755, 277886.782 81..."
4,DARTMOUTH,72,24840,27244,30666,3422,T,1,NO,4,...,25005020,5,0.260,0.000,34032,3366,2404,1.053604e+03,131.624579,"POLYGON ((245000.002 815602.875, 245003.153 81..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234,NAHANT,196,3922,3828,3632,-196,T,1,NO,2,...,25009105,9,0.950,0.002,3410,-222,-94,3.843179e+03,321.605460,"POLYGON ((248661.193 907368.815, 248657.083 90..."
1235,NEW BRAINTREE,202,682,881,927,46,T,0,NO,3,...,25027155,27,13387.175,20.917,999,72,199,5.417596e+07,42901.962904,"POLYGON ((149542.763 900839.425, 155382.932 89..."
1236,EASTHAM,86,3890,4462,5453,991,T,1,NO,4,...,25001030,1,0.293,0.001,4956,-497,572,1.184125e+03,140.564687,"POLYGON ((324154.633 840811.065, 324154.002 84..."
1237,ANDOVER,9,27203,29151,31247,2096,T,0,YES,3,...,25009010,9,207.189,0.324,33201,1954,1948,8.384623e+05,18518.700347,"POLYGON ((225495.502 938455.005, 225513.203 93..."
1238,MARION,169,4027,4496,5123,627,T,1,NO,4,...,25023070,23,2.388,0.004,4907,-216,469,9.664744e+03,666.816427,"POLYGON ((261679.593 825526.185, 261682.333 82..."

In [3]:
geometry_column = "geometry"

In [4]:
gdf['latitude'] = gdf.centroid.y
gdf['longitude'] = gdf.centroid.x